# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 0.7

notifications:
    email:
      recipients:
        - donsadit@gmail.com
        - kyriox@gmail.com
        - mgraffg@gmail.com
        - sabinomiranda@gmail.com
        - dmocteo@gmail.com

    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("NNS"); Pkg.test("NNS"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("SimilaritySearch")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("SimilaritySearch")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
