name = "SimilaritySearch"
uuid = "7eee491e-8ade-11e8-359b-2102e3160632"
authors = ["Eric S. Tellez <donsadit@gmail.com>"]
version = "0.1.8"

[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
