name = "SimilaritySearch"
uuid = "053f045d-5466-53fd-b400-a066f88fe02a"
authors = ["Eric S. Tellez <donsadit@gmail.com>"]
version = "0.11.10"

[deps]
AllocCheck = "9b6a8646-10ed-4001-bbdc-1d2f46dfbb1a"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SearchModels = "0e966ebe-b704-4a65-8279-db954bfe5da0"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StrideArraysCore = "7792a7ef-975c-4747-a70f-980b88e8d1da"

[compat]
AllocCheck = "0.2"
Aqua = "0.8"
Dates = "^1.0"
Distances = "0.10"
JET = "0.9"
JLD2 = "0.4"
LinearAlgebra = "^1.0"
Parameters = "0.12"
Polyester = "0.7"
Random = "^1.0"
SearchModels = "0.4"
SparseArrays = "^1.0"
Statistics = "^1.0"
StatsBase = "0.32 - 0.34"
StrideArraysCore = "0.5"
Test = "^1.0"
julia = "^1.8"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SparseArrays", "Aqua", "JET"]
