[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
FixedSizeArrays = "3821ddf9-e5b5-40d5-8e25-6813ab96b5e2"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
SimilaritySearch = "053f045d-5466-53fd-b400-a066f88fe02a"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
SimilaritySearch = {path = ".."}
